[package]
name = "vga_buffer_driver"
version = "0.1.7"
edition = "2024"

[dependencies]
lazy_static = {version = "1.5.0", features = ["spin_no_std"]}
volatile = {version = "0.6.1"}

[features]
no_std = []